name: Deploy to Production VPS

on:
  push:
    branches:
      - main # Větev, při jejíž změně se spustí akce
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Production VPS
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$KEY" > ~/.ssh/id_rsa_deploy
        chmod 600 ~/.ssh/id_rsa_deploy
        rsync -avz --delete $GITHUB_WORKSPACE/ $USER@$HOST:/var/www/html/wp-content/themes/pedrodiary/
