name: Deploy to Production VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Production VPS
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo -n "$KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        cat ~/.ssh/id_rsa
        ls -l ~/.ssh/id_rsa

        rsync -av --delete -e "ssh -i ~/.ssh/id_rsa" $GITHUB_WORKSPACE/ $USER@$HOST:/var/www/html/wp-content/themes/pedrodiary