name: Deploy to Production
on:
  push:
    branches:
      - main # Větev, při jejíž změně se spustí akce

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Server
      env:
        HOST: ${{ secrets.HOST }} # Hostname produkčního serveru
        USERNAME: ${{ secrets.USERNAME }} # Uživatelské jméno na serveru    
        KEY: ${{ secrets.SERVER_SSH_KEY }} # Privátní SSH klíč pro připojení
        
      run: |
        mkdir -p ~/.ssh/
        echo "$KEY" > ~/.ssh/id_ecdsa
        chmod 600 ~/.ssh/id_ecdsa
        
        scp -r * $USERNAME@$HOST:/var/www/html/wp-content/themes/pedrodiary/
