name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."  # Lokální složka ve které se nachází kód
        target: "/var/www/html/wp-content/themes/pedrodiary/"  # Cílová složka na VPS
